### ISSUE TITLE
Set up read.me

### ISSUE THREAD

**Issue by helms-charity** [hlxsites/fresenius#1]
It is good to get the site's important links in there:
- the .page
- the .live
- the original site
- any special instructions or call outs
- a pre-made Sidekick link is nice too

Please add links to these pages as ones we plan to build out in Franklin:
https://www.freseniusmedicalcare.com/en/home
https://www.freseniusmedicalcare.com/en/patients-families-overview
https://www.freseniusmedicalcare.com/en/dialysis-options

**Comment by spaciouskarter78** [comment]
newbie here, i want to contribute. Can you tell me what exactly to add?

**Comment by Toto-Tuo** [comment]
I am taking this one, newbie here LOL.
