### ISSUE TITLE
Page: en/living-with-dialysis

### ISSUE THREAD

**Issue by helms-charity** [hlxsites/fresenius#14]
This page has an accordion on it.

https://www.freseniusmedicalcare.com/en/living-with-dialysis

**Comment by Toto-Tuo** [comment]
@helms-charity 

I did the content, but not  sure on the accordions, take a look at it and let me know?
Thanks you!

**Comment by helms-charity** [comment]
Thanks for the reminder to create a ticket for the Accordion block :-)
https://github.com/hlxsites/fresenius/issues/47

I fixed your block table in the Word doc and added a blank one for you to continue pasting the content into so you can finish up. Thank you!

**Comment by Toto-Tuo** [comment]
Thanks @helms-charity :-)
Added Accordion contents.

**Comment by helms-charity** [comment]
https://main--fresenius--hlxsites.hlx.page/living-with-dialysis
