### ISSUE TITLE
Page: en/media/insights/company-features/united-by-a-shared-purpose

### ISSUE THREAD

**Issue by helms-charity** [hlxsites/fresenius#18]
This is linked from the home page "stories" carousel, 1st story.
Has a pullquote block on it.

https://www.freseniusmedicalcare.com/en/media/insights/company-features/united-by-a-shared-purpose

**Comment by Toto-Tuo** [comment]
Created content.

**Comment by helms-charity** [comment]
DONE https://main--fresenius--hlxsites.hlx.page/united-by-a-shared-purpose
