### ISSUE TITLE
Style: Sections spacing

### ISSUE THREAD

**Issue by helms-charity** [hlxsites/fresenius#33]
The boilerplate has 
`main .section { padding: 64px 16px; }`
but the Fresenius site uses only a bottom padding.

Change to `padding-bottom: 4rem` for mobile, 5rem for min-width: 1024px in styles.css.

![image](https://github.com/hlxsites/fresenius/assets/3883795/0741d8c0-0d15-4707-8e8b-3a0f138c7587)

**Comment by Nkiriobasi** [comment]
I’ll fix this

**Comment by helms-charity** [comment]
Closing, fixed with PR #37 .
