### ISSUE TITLE
Embed block: Test with mp4

### ISSUE THREAD

**Issue by helms-charity** [hlxsites/fresenius#35]
This is a follow up ticket to https://github.com/hlxsites/fresenius/pull/34 where the embed block was created. 

Now, create a directory for yourself under /drafts/yourname in Sharepoint, and create a test page with an embed block on it.
To add an mp4 video to the codebus, follow instructions here https://www.hlx.live/docs/slack#upload-files .

The source MP4 file can be found on this page: https://www.freseniusmedicalcare.com/en/dialysis-options

**Comment by Toto-Tuo** [comment]
@helms-charity 

This doesn't require code changes. Do we still need to create a branch and create PR?

The steps I took:
Configured Franklin Bot for the slack channel and fresenius Sharepoint site.
Downloaded video from client site and uploaded to Sharepoint via Franklin bot
Src URL:
https://www.freseniusmedicalcare.com/fileadmin/data/masterContent/video/Understanding_peritoneal_dialysis/Understanding_Peritoneal_Dialysis_EN.mp4

Target URL:
https://main--fresenius--hlxsites.hlx.page/media_1e5decba9b1223da974b92438083178301238c4ac.mp4 

Created test page , Previewed and tested the page -
https://main--fresenius--hlxsites.hlx.page/drafts/tuo/test-video

Thank you!

**Comment by helms-charity** [comment]
it might need some tweaking. Do you see it turn into a tiny video when you press play for a second before it gets big again?

**Comment by Toto-Tuo** [comment]
Thanks @helms-charity !
I think the styling needs some tweak , as I can see the video is not centered in browser window on my desktop.
I will try to look into that.

**Comment by Toto-Tuo** [comment]
@helms-charity 
I fixed the video not centered issue (by adjusting the width in embed.css) .
But I am a bit lost at figuring out that tiny video issue after first click play .
Any pointers you can let me know to where I should look at that? 
Thank you :-)

**Comment by helms-charity** [comment]
Not really :-) I think you can do a PR for your CSS fix and we can revisit that later as an "enhancement".

**Comment by Toto-Tuo** [comment]
Thanks @helms-charity  :-)

Created PR.
